[package]
name = "meister-crosvm-gpu-driver"
version = "0.1.0"
edition = "2024"

[dependencies]
agent-api = { package = "meister-agent-api", path = "../../shared/agent-api" }
backend = { package = "meister-backend", path = "../backend" }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
