[package]
name = "meister-filesystem-driver"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
agent-api = { package = "meister-agent-api", path = "../../shared/agent-api" }
macros = { package = "meister-macros", path = "../../shared/macros" }
async-trait = { workspace = true }
anyhow = { workspace = true }
nix = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
