// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Silas Müller <github@silasmueller.de>
// SPDX-FileCopyrightText: 2026 Universität Stuttgart, IKR

//! A node of this fleet, as a file somebody else's NixOS configuration can
//! import.
//!
//! Almost every real box already has a configuration: a driver, a firmware, a
//! kernel, a `hardware-configuration.nix` that was generated on the metal.
//! Those hosts do not want our image and they should not have to give up
//! their own configuration to be part of a fleet. So this writes the OTHER
//! half — what this stack knows about that node and nothing else — and the
//! host's own configuration imports it next to `nixosModules.default`:
//!
//!   imports = [
//!     ./hardware-configuration.nix
//!     meisterstack.nixosModules.default
//!     ./agent-1a.nix              # <- this file
//!   ];
//!
//! What is deliberately NOT in here: hardware, bootloaders, filesystems,
//! addresses, drivers. Those belong to the host, and a fleet tool that writes
//! them is a fleet tool that breaks somebody's boot.
//!
//! A pure function of the plan. No ssh, no nix, no detection: the plan is the
//! truth, not the host — a node that has drifted from the plan is a finding,
//! not a new plan. And byte-identical for the same plan, so the result
//! belongs in a repository next to the configuration that imports it.

use std::collections::BTreeMap;

use crate::fleet::{Node, Plan, Role};

/// The MeisterStack options for one node, as a Nix module.
pub fn module(plan: &Plan, node: &Node) -> String {
    let mut out = String::new();
    out.push_str("# SPDX-License-Identifier: MIT\n#\n");
    out.push_str(&format!(
        "# {} of the fleet {:?} — generated by `meister-deploy render {}`.\n",
        node.name, plan.fleet.name, node.name
    ));
    out.push_str(
        "#\n# Edit the plan, not this file: it is a pure function of fleet.toml and the\n\
         # next render overwrites it. Import it next to\n\
         # `meisterstack.nixosModules.default` and this host is that node.\n\
         #\n# It carries no hardware, no bootloader, no filesystem and no address —\n\
         # those are the host's own, and this file has no business in them.\n#\n",
    );
    out.push_str("{\n");

    let mut top: BTreeMap<String, String> = BTreeMap::new();
    top.insert(
        "meisterstack.roles".to_string(),
        list(node.roles.iter().map(|r| r.as_str().to_string())),
    );

    // MEISTER_ROLE is left out on purpose: `meisterstack.roles` above is what
    // derives it (nix/roles.nix), and writing it here as well would be two
    // owners for one variable.
    let mut env = plan.context_env(node);
    env.remove("MEISTER_ROLE");
    top.insert("meisterstack.context.defaults".to_string(), attrs(&env, 2));

    for role in [Role::Cloud, Role::Cluster, Role::Agent] {
        if !node.has(role) {
            continue;
        }
        if let Some(table) = node.settings.get(role.as_str()) {
            top.insert(
                format!("meisterstack.{}.settings", role),
                toml_table(table, 2),
            );
        }
    }

    if node.has(Role::Addons) {
        if let Some(host) = plan.addons_host() {
            top.insert("meisterstack.addons.fqdn".to_string(), string(&host));
        }
        top.insert(
            "meisterstack.addons.scrapeTargets".to_string(),
            list(plan.scrape_targets()),
        );
    }

    if node.data.is_some() {
        top.insert(
            "meisterstack.data.label".to_string(),
            string("meister-data"),
        );
    }

    for (key, value) in &top {
        out.push_str(&format!("  {key} = {value};\n"));
    }
    out.push_str("}\n");
    out
}

fn string(s: &str) -> String {
    let escaped = s
        .replace('\\', r"\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace("${", "\\${");
    format!("\"{escaped}\"")
}

fn list<I: IntoIterator<Item = String>>(items: I) -> String {
    let inner: Vec<String> = items.into_iter().map(|s| string(&s)).collect();
    if inner.is_empty() {
        "[ ]".to_string()
    } else {
        format!("[ {} ]", inner.join(" "))
    }
}

fn attrs(map: &BTreeMap<String, String>, indent: usize) -> String {
    if map.is_empty() {
        return "{ }".to_string();
    }
    let pad = " ".repeat(indent);
    let mut out = String::from("{\n");
    for (k, v) in map {
        out.push_str(&format!("{pad}  {k} = {};\n", string(v)));
    }
    out.push_str(&format!("{pad}}}"));
    out
}

/// Free-form TOML, as Nix. Sorted, because the file has to be byte-identical
/// for the same plan and a hash map is not.
fn toml_table(table: &toml::Table, indent: usize) -> String {
    if table.is_empty() {
        return "{ }".to_string();
    }
    let pad = " ".repeat(indent);
    let sorted: BTreeMap<&String, &toml::Value> = table.iter().collect();
    let mut out = String::from("{\n");
    for (k, v) in sorted {
        out.push_str(&format!("{pad}  {k} = {};\n", toml_value(v, indent + 2)));
    }
    out.push_str(&format!("{pad}}}"));
    out
}

fn toml_value(value: &toml::Value, indent: usize) -> String {
    match value {
        toml::Value::String(s) => string(s),
        toml::Value::Integer(i) => i.to_string(),
        toml::Value::Float(f) => f.to_string(),
        toml::Value::Boolean(b) => b.to_string(),
        toml::Value::Datetime(d) => string(&d.to_string()),
        toml::Value::Array(a) => {
            let inner: Vec<String> = a.iter().map(|v| toml_value(v, indent)).collect();
            if inner.is_empty() {
                "[ ]".to_string()
            } else {
                format!("[ {} ]", inner.join(" "))
            }
        }
        toml::Value::Table(t) => toml_table(t, indent),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const PLAN: &str = r#"
[fleet]
name = "one-box"
domain = "lab.example"

[[node]]
name = "box"
group = "box"
roles = ["cloud", "cluster", "agent", "addons"]
address = "10.0.0.10"
disk = "/dev/vda"
data = "/dev/vdb"
settings.cloud.csr_auto_approve = true
settings.agent.stop_grace_secs = 45

[[node]]
name = "n1"
group = "box"
address = "10.0.0.11"
"#;

    fn plan() -> Plan {
        Plan::parse(PLAN).unwrap()
    }

    #[test]
    fn a_rendered_node_carries_its_roles_its_context_and_its_settings() {
        let p = plan();
        let text = module(&p, p.node("box").unwrap());
        assert!(
            text.contains(r#"meisterstack.roles = [ "agent" "cluster" "cloud" "addons" ];"#),
            "{text}"
        );
        assert!(text.contains(r#"MEISTER_CLUSTER_NAME = "box";"#), "{text}");
        assert!(
            text.contains(
                r#"MEISTER_OIDC_ISSUER = "https://box.lab.example:8443/oauth2/openid/meister-cli";"#
            ),
            "{text}"
        );
        assert!(text.contains("csr_auto_approve = true;"), "{text}");
        assert!(text.contains("stop_grace_secs = 45;"), "{text}");
        assert!(
            text.contains(r#"meisterstack.addons.fqdn = "box.lab.example";"#),
            "{text}"
        );
        assert!(
            text.contains(r#"meisterstack.data.label = "meister-data";"#),
            "{text}"
        );
    }

    #[test]
    fn meister_role_is_not_written_twice() {
        let p = plan();
        let text = module(&p, p.node("box").unwrap());
        assert!(
            !text.contains("MEISTER_ROLE"),
            "meisterstack.roles derives it; two owners for one variable is a conflict:\n{text}"
        );
    }

    #[test]
    fn nothing_about_the_host_is_in_it() {
        let p = plan();
        let text = module(&p, p.node("box").unwrap());
        // The body, not the header: the header says in prose that none of
        // this is in here, and a test that reads its own explanation as
        // evidence is not a test.
        let text = &text[text.find("{\n").expect("the module opens somewhere")..];
        for forbidden in [
            "fileSystems",
            "boot.loader",
            "networking.interfaces",
            "hardware",
            "/dev/vda",
        ] {
            assert!(
                !text.contains(forbidden),
                "{forbidden:?} belongs to the host, not to us:\n{text}"
            );
        }
    }

    #[test]
    fn the_same_plan_renders_the_same_bytes() {
        let a = module(&plan(), plan().node("box").unwrap());
        let b = module(&plan(), plan().node("box").unwrap());
        assert_eq!(a, b, "a file that belongs in a repository has to be stable");
    }

    #[test]
    fn a_plain_agent_gets_its_controllers_and_no_issuer() {
        let p = plan();
        let text = module(&p, p.node("n1").unwrap());
        assert!(
            text.contains(r#"meisterstack.roles = [ "agent" ];"#),
            "{text}"
        );
        assert!(
            text.contains(r#"MEISTER_CONTROLLER_ADDRS = "10.0.0.10:50051";"#),
            "{text}"
        );
        assert!(
            !text.contains("OIDC"),
            "an agent authenticates nobody:\n{text}"
        );
        assert!(!text.contains("addons"), "{text}");
    }

    #[test]
    fn a_string_that_looks_like_nix_is_still_a_string() {
        assert_eq!(string("a${b}c"), r#""a\${b}c""#);
        assert_eq!(string(r#"say "hi""#), r#""say \"hi\"""#);
    }
}
