// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Silas Müller <github@silasmueller.de>
// SPDX-FileCopyrightText: 2026 Universität Stuttgart, IKR

//! Pure translation from instance resources and sandbox policy to the
//! Cloud Hypervisor JSON configuration.

use super::*;

/// Build a disk entry, or None for a filesystem share. Path attachments are
/// raw files or block devices; explicitly use the case-sensitive `Raw` variant
/// to avoid format autodetection and its sector-zero write restrictions.
/// A driver returning another format would need a corresponding contract change.
pub(crate) fn disk_config(disk: &AttachedVolume) -> Option<serde_json::Value> {
    let mut config = match &disk.attachment {
        VolumeAttachment::Path(path) => serde_json::json!({
            "path": path,
            "image_type": "Raw",
        }),
        VolumeAttachment::VhostUserBlk { socket, .. } => serde_json::json!({
            "vhost_user": true,
            "vhost_socket": socket,
        }),
        VolumeAttachment::FsShare { .. } => return None,
    };
    // Assign stable IDs from volume IDs so unplug and resize do not depend on
    // Cloud Hypervisor's autogenerated positional disk names.
    config["id"] = agent_api::disk_id(&disk.id).into();
    Some(config)
}

/// Keep block disks in specification order and append the read-only seed.
/// The seed must not displace the boot disk or accept writes that would be lost
/// when it is regenerated.
pub(crate) fn disks(spec: &InstanceSpec) -> Vec<serde_json::Value> {
    let mut disks: Vec<serde_json::Value> = spec.volumes.iter().filter_map(disk_config).collect();
    if let Some(seed) = &spec.cloud_init_seed {
        // Declare the FAT12 seed as Raw to avoid format autodetection.
        disks.push(serde_json::json!({
            "path": seed,
            "readonly": true,
            "image_type": "Raw",
        }));
    }
    disks
}

/// One entry of CH's `fs` array: virtiofsd is already listening on `socket`,
/// and `tag` is the name the guest mounts (`mount -t virtiofs <tag> /mnt`).
/// `num_queues` and `queue_size` are CH's own defaults and are left to it.
pub(crate) fn fs_config(volume: &VolumeAttachment) -> Option<serde_json::Value> {
    match volume {
        VolumeAttachment::FsShare { socket, tag, .. } => {
            Some(serde_json::json!({ "socket": socket, "tag": tag }))
        }
        _ => None,
    }
}

/// NIC handoff by persistent tap name or an SCM_RIGHTS descriptor.
///
/// Descriptor handoff lets a VMM use a tap without CAP_NET_ADMIN. The supported
/// Cloud Hypervisor receive protocol discards transferred fd numbers and offers
/// no replacement channel, so fd-backed NICs cannot use live migration.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub(crate) enum NetForm {
    /// `"net": [{"tap": "msk…"}]` in `vm.create`. The VMM opens
    /// `/dev/net/tun` itself and needs the right to.
    TapName,
    /// `vm.create` without `net`, then one `vm.add-net` per NIC carrying the
    /// open tap as `SCM_RIGHTS`. See `fd.rs`.
    TapFd,
}

/// One `landlock_rules` entry: a path the VMM may reach, and how.
#[derive(Clone, PartialEq, Eq, Debug)]
pub(crate) struct LandlockRule {
    pub(crate) path: PathBuf,
    /// `"r"` or `"rw"`, which is CH's own spelling
    /// (`--landlock-rules "path=…,access=[rw]"`).
    pub(crate) access: &'static str,
}

/// What shape of VM document this driver is building: how the NICs arrive,
/// and whether the VMM sandboxes itself.
#[derive(Clone, PartialEq, Eq, Debug)]
pub(crate) struct VmForm {
    pub(crate) net: NetForm,
    /// Enable Landlock and extend Cloud Hypervisor's config-derived rules with
    /// directories needed for later file-backed hotplug. None disables Landlock.
    pub(crate) landlock: Option<Vec<LandlockRule>>,
}

pub(crate) fn build_vm_config(
    spec: &InstanceSpec,
    console_path: &PathBuf,
    serial_socket: &PathBuf,
    form: &VmForm,
) -> hypervisor::Result<serde_json::Value> {
    let net_form = form.net;
    // Any vhost-user device or volume requires shared guest memory.
    let has_vhost_user = spec
        .devices
        .iter()
        .any(DeviceAttachment::needs_shared_memory)
        || spec
            .volumes
            .iter()
            .any(|v| v.attachment.needs_shared_memory());

    // handle optional kernel & initramfs for direct-kernel boot, not required for UEFI boot
    let payload = match &spec.boot {
        BootSource::DirectKernel {
            kernel,
            cmdline,
            initramfs,
        } => {
            let mut p = serde_json::json!({ "kernel": kernel, "cmdline": cmdline });
            if let Some(i) = initramfs {
                p["initramfs"] = serde_json::json!(i);
            }
            p
        }
        BootSource::Firmware { firmware } => serde_json::json!({ "firmware": firmware }),
    };

    let mut config = serde_json::json!({
        "cpus":   { "boot_vcpus": spec.vcpus, "max_vcpus": spec.vcpus },
        "memory": {
            "size": spec.memory_mib * 1024 * 1024,
            "shared": has_vhost_user,
        },
        "payload": payload,
        "disks":  disks(spec),
        // Virtio-console writes directly to a file. The interactive UART uses a
        // socket that the agent records; Cloud Hypervisor v53 buffers up to 1 MiB
        // while no reader is connected.
        "console": { "mode": "File", "file": console_path },
        "serial": { "mode": "Socket", "socket": serial_socket }

    });

    let shares: Vec<_> = spec
        .volumes
        .iter()
        .filter_map(|v| fs_config(&v.attachment))
        .collect();
    if !shares.is_empty() {
        config["fs"] = shares.into();
    }

    // Name-based NICs belong in vm.create; descriptor-backed NICs follow through vm.add-net.
    if net_form == NetForm::TapName && !spec.nics.is_empty() {
        config["net"] = spec
            .nics
            .iter()
            .map(|n| {
                let mut net = serde_json::json!({ "tap": n.tap_name, "mac": n.mac.to_string() });
                // Advertise the host path MTU through VIRTIO_NET_F_MTU so the guest
                // does not emit frames larger than the overlay permits.
                if let Some(mtu) = n.mtu {
                    net["mtu"] = serde_json::Value::from(mtu);
                }
                net
            })
            .collect::<Vec<_>>()
            .into();
    }

    let mut vhost_user_devices = Vec::new();
    let mut vfio_devices = Vec::new();
    for dev in &spec.devices {
        match dev {
            DeviceAttachment::VhostUser {
                socket,
                device_type,
                queue_sizes,
                ..
            } => {
                vhost_user_devices.push(serde_json::json!({
                    "socket": socket,
                    "device_type": device_type,
                    "queue_sizes": queue_sizes,
                }));
            }
            DeviceAttachment::VfioPci { sysfs_path } => {
                vfio_devices.push(serde_json::json!({ "path": sysfs_path }));
            }
            other => {
                return Err(HypervisorError::InvalidSpec(format!(
                    "attachment type not yet supported by CH driver: {other:?}"
                )));
            }
        }
    }
    if !vhost_user_devices.is_empty() {
        config["generic_vhost_user"] = vhost_user_devices.into();
    }
    if !vfio_devices.is_empty() {
        config["devices"] = vfio_devices.into();
    }

    // API-driven VMMs enable Landlock in vm.create. The CLI --landlock flag
    // requires command-line boot configuration and cannot be used with this spawn form.
    if let Some(rules) = &form.landlock {
        config["landlock_enable"] = true.into();
        if !rules.is_empty() {
            config["landlock_rules"] = rules
                .iter()
                .map(|r| serde_json::json!({ "path": r.path, "access": r.access }))
                .collect::<Vec<_>>()
                .into();
        }
    }
    Ok(config)
}

/// Build the body accompanying one tap descriptor. Omit `tap` and `fds`: the
/// SCM_RIGHTS message supplies the open device. Omit MTU to avoid a privileged
/// set-MTU ioctl in the VMM; it reads the configured tap MTU instead.
///
/// One descriptor requires two queues. The guest MAC travels explicitly, and
/// the tap name provides a stable device ID.
pub(crate) fn net_config(nic: &agent_api::NicAttachment) -> serde_json::Value {
    serde_json::json!({
        "id": nic.tap_name,
        "mac": nic.mac.to_string(),
        "num_queues": 2,
    })
}
