# SPDX-License-Identifier: MIT
#
# box of the fleet "one-box" — generated by `meister-deploy render box`.
#
# Edit the plan, not this file: it is a pure function of fleet.toml and the
# next render overwrites it. Import it next to
# `meisterstack.nixosModules.default` and this host is that node.
#
# It carries no hardware, no bootloader, no filesystem and no address —
# those are the host's own, and this file has no business in them.
#
{
  meisterstack.addons.fqdn = "box.lab.example";
  meisterstack.addons.scrapeTargets = [ "10.0.0.10:9102" "10.0.0.10:9101" "10.0.0.10:9100" "10.0.0.11:9102" "10.0.0.12:9102" ];
  meisterstack.context.defaults = {
    MEISTER_CLOUD_ADDRS = "10.0.0.10:50050";
    MEISTER_CLOUD_ADVERTISE_API = "10.0.0.10:3000";
    MEISTER_CLOUD_NAME = "box";
    MEISTER_CLUSTER_ADVERTISE_API = "10.0.0.10:3001";
    MEISTER_CLUSTER_NAME = "box";
    MEISTER_CONTROLLER_ADDRS = "10.0.0.10:50051";
    MEISTER_HOSTS = "10.0.0.10 box.lab.example";
    MEISTER_LOG_FORMAT = "json";
    MEISTER_LOKI_URL = "http://10.0.0.10:3100/loki/api/v1/push";
    MEISTER_OIDC_AUDIENCE = "meister-cli";
    MEISTER_OIDC_CA = "/opt/meisterstack/pki/ca.crt";
    MEISTER_OIDC_ISSUER = "https://box.lab.example:8443/oauth2/openid/meister-cli";
    MEISTER_OTLP_ENDPOINT = "http://10.0.0.10:4317";
  };
  meisterstack.data.label = "meister-data";
  meisterstack.roles = [ "agent" "cluster" "cloud" "addons" ];
}
